[package]
name = "rama-socks5"
description = "SOCKS5 support for rama"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = ["io", "async", "socks5", "network", "rama"]
categories = ["asynchronous", "network-programming", "web-programming"]
authors = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[features]
default = []
dns = ["dep:rama-dns", "dep:rand"]

[dependencies]
bytes = { workspace = true }
rama-core = { version = "0.2.0-alpha.13", path = "../rama-core" }
rama-dns = { version = "0.2.0-alpha.13", path = "../rama-dns", optional = true }
rama-net = { version = "0.2.0-alpha.13", path = "../rama-net", features = ["http"] }
rama-tcp = { version = "0.2.0-alpha.13", path = "../rama-tcp", features = ["http"] }
rama-udp = { version = "0.2.0-alpha.13", path = "../rama-udp" }
rama-utils = { version = "0.2.0-alpha.13", path = "../rama-utils" }
rand = { workspace = true, optional = true }
smallvec = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }

[package.metadata.cargo-public-api-crates]
allowed = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
